name: Backend CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. React 프로젝트와 백엔드 동기화
    - name: Sync Files to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        rsync -avz --progress \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude 'README.md' \
          --exclude '*.md' \
          --exclude '.idea/' \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/ftt_backend/

        rsync -avz --progress \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          ./ftt_frontend/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/ftt_frontend/

    # 3. 빌드 및 애플리케이션 재시작
    - name: Build and Restart Application
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # React 빌드
          cd /home/ubuntu/ftt_frontend
          npm install
          npm run build

          # React 빌드 결과물 복사
          cp -r build/* /home/ubuntu/ftt_backend/src/main/resources/static/

          # Gradle 빌드
          cd /home/ubuntu/ftt_backend
          chmod +x ./gradlew
          ./gradlew clean build -x test

          # 기존 애플리케이션 중지
          pkill -f 'java -jar' || true

          # 새로운 애플리케이션 실행
          nohup java -jar build/libs/*.jar > /dev/null 2>&1 &
