name: Backend CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    # 1. 체크 아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Sync Changed Files to EC2
    - name: Sync Changed Files to EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        rsync -avz --progress \
          --exclude '.git/' \
          --exclude '.github/' \
          --exclude 'README.md' \
          --exclude '*.md' \
          --exclude '.idea/' \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/ftt_backend/

    # 3. Build and Restart Application
    - name: Build and Restart Application
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Move to backend directory
          cd /home/ubuntu/ftt_backend/

          # Gradle Wrapper에 실행 권한 추가
          chmod +x ./gradlew
        
          # Gradle 빌드
          echo "Building backend application..."
          ./gradlew clean build -x test
        
          # 기존 애플리케이션 중지
          echo "Stopping existing application..."
          pkill -f 'java -jar' || true
        
          # 새로운 애플리케이션 실행
          echo "Starting new application..."
          nohup java -jar build/libs/*.jar > /dev/null 2>&1 &
