name: Backend CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 변경된 파일만 EC2 서버로 동기화
    - name: Sync Changed Files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "*"
        target: "/home/ubuntu/ftt_backend/"
        exclude: |
          .git/**
          .github/**
          README.md
          *.md
          .idea/**

    # 3. 서버에서 빌드 및 애플리케이션 재시작
    - name: Build and Restart Application
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 경로 이동
          cd /home/ubuntu/ftt_backend/

          # Gradle 빌드
          echo "Building backend application..."
          ./gradlew clean build -x test

          # 기존 애플리케이션 종료
          echo "Stopping existing application..."
          pkill -f 'java -jar' || true

          # 새로운 애플리케이션 실행
          echo "Starting new application..."
          nohup java -jar build/libs/*.jar > /dev/null 2>&1 &
